import { StyleSheet } from "react-native";

export const GREEN_DARK = "#346739";
export const GREEN_MED = "#79AE6F";

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: "#fff",
  },
  header: {
    paddingHorizontal: 20,
    paddingBottom: 0,
    alignItems: "center",
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
  },
  headerInner: {
    width: "100%",
    maxWidth: 480,
    paddingBottom: 24,
  },
  headerTitle: {
    fontFamily: "Nunito_900Black",
    fontSize: 28,
    color: "#fff",
    textAlign: "center",
    marginBottom: 16,
  },
  summaryRow: {
    flexDirection: "row",
    gap: 12,
    marginTop: 16,
  },
  summaryCard: {
    flex: 1,
    borderRadius: 14,
    padding: 16,
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.12)",
  },
  summaryCardLabel: {
    fontFamily: "Nunito_700Bold",
    fontSize: 11,
    color: "rgba(255,255,255,0.8)",
    marginBottom: 4,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  summaryCardAmount: {
    fontFamily: "Nunito_900Black",
    fontSize: 20,
    color: "#fff",
  },
  list: {
    flex: 1,
  },
  listContent: {
    padding: 16,
    paddingBottom: 100,
    maxWidth: 480,
    width: "100%",
    alignSelf: "center",
  },
  // Goal card
  card: {
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.07,
    shadowRadius: 8,
    elevation: 3,
  },
  cardHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
  },
  colorDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    marginRight: 10,
  },
  cardName: {
    fontFamily: "Nunito_800ExtraBold",
    fontSize: 16,
    color: "#333",
    flex: 1,
  },
  completedBadge: {
    fontFamily: "Nunito_700Bold",
    fontSize: 11,
    color: "#fff",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 10,
    overflow: "hidden",
    marginRight: 8,
  },
  menuBtn: {
    padding: 4,
  },
  amountsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  amountSaved: {
    fontFamily: "Nunito_700Bold",
    fontSize: 14,
    color: "#333",
  },
  amountTarget: {
    fontFamily: "Nunito_600SemiBold",
    fontSize: 13,
    color: "#999",
  },
  deadline: {
    fontFamily: "Nunito_600SemiBold",
    fontSize: 12,
    color: "#bbb",
    marginBottom: 8,
  },
  progressTrack: {
    height: 10,
    backgroundColor: "#F0F0F0",
    borderRadius: 5,
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    borderRadius: 5,
  },
  // FAB
  fab: {
    position: "absolute",
    bottom: 32,
    right: 24,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: GREEN_DARK,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 8,
  },
  // ─── Modals shared (backdrop + Create Goal / Add Funds — Task 4) ──────────────
  backdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.45)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalCard: {
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 24,
    width: "90%",
    maxWidth: 320,
  },
  modalTitle: {
    fontFamily: "Nunito_900Black",
    fontSize: 20,
    color: "#333",
    textAlign: "center",
    marginBottom: 20,
  },
  fieldLabel: {
    fontFamily: "Nunito_700Bold",
    fontSize: 13,
    color: "#555",
    marginBottom: 6,
  },
  textInput: {
    borderWidth: 1.5,
    borderColor: "#E0E0E0",
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
    fontFamily: "Nunito_600SemiBold",
    fontSize: 15,
    color: "#333",
    marginBottom: 14,
  },
  // Color picker grid
  colorGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginBottom: 14,
  },
  colorSwatch: {
    width: 30,
    height: 30,
    borderRadius: 15,
    justifyContent: "center",
    alignItems: "center",
  },
  // Modal buttons
  modalButtons: {
    flexDirection: "row",
    gap: 10,
    marginTop: 4,
  },
  cancelBtn: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: "#F5F5F5",
    alignItems: "center",
  },
  cancelText: {
    fontFamily: "Nunito_700Bold",
    fontSize: 15,
    color: "#666",
  },
  saveBtn: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: GREEN_DARK,
    alignItems: "center",
  },
  saveText: {
    fontFamily: "Nunito_700Bold",
    fontSize: 15,
    color: "#fff",
  },
  // Action menu card
  actionCard: {
    backgroundColor: "#fff",
    borderRadius: 16,
    paddingVertical: 8,
    width: 220,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 12,
  },
  actionCardTitle: {
    fontFamily: "Nunito_800ExtraBold",
    fontSize: 15,
    color: "#333",
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  actionDivider: {
    height: 1,
    backgroundColor: "rgba(0,0,0,0.07)",
    marginHorizontal: 8,
    marginBottom: 4,
  },
  actionItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 16,
    paddingVertical: 13,
    borderRadius: 10,
    marginHorizontal: 4,
  },
  actionItemPressed: {
    backgroundColor: "rgba(52,103,57,0.08)",
  },
  actionItemText: {
    fontFamily: "Nunito_700Bold",
    fontSize: 14,
    color: "#333",
  },
  actionItemTextDanger: {
    color: "#E74C3C",
  },
  emptyText: {
    fontFamily: "Nunito_600SemiBold",
    fontSize: 15,
    color: "#bbb",
    textAlign: "center",
    marginTop: 48,
  },
});
