import { Platform, StyleSheet } from "react-native";

export const marketing = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#346739",
  },
  containerWeb: {
    minHeight: "100vh" as any,
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.12)",
    zIndex: 1,
  },
  petalsLayer: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 2,
  },
  content: {
    alignItems: "center",
    paddingHorizontal: 24,
    gap: 4,
  },
  taglineWrap: {
    backgroundColor: "rgba(0,0,0,0.22)",
    borderRadius: 20,
    overflow: "hidden",
    marginTop: 2,
    marginBottom: 22,
  },
  tagline: {
    fontSize: 15,
    fontFamily: "Nunito_800ExtraBold",
    color: "#ffffff",
    letterSpacing: 1.2,
    textTransform: "uppercase",
    textShadowColor: "rgba(0,0,0,0.55)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 6,
    textAlign: "center",
    paddingHorizontal: 18,
    paddingVertical: 6,
  },
  pulseRing: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 50,
    borderWidth: 2,
    borderColor: "rgba(255,255,255,0.8)",
  },
  btnWrapper: {
    alignItems: "center",
  },
  ctaButton: {
    backgroundColor: "#ffffff",
    paddingVertical: 11,
    paddingHorizontal: 30,
    borderRadius: 50,
    alignItems: "center",
    shadowColor: "#ffffff",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.55,
    shadowRadius: 14,
    elevation: 8,
    borderWidth: 1.5,
    borderColor: "rgba(255,255,255,0.6)",
  },
  ctaButtonPressed: {
    backgroundColor: "#ffffff",
    transform: [{ scale: 0.97 }],
  },
  ctaText: {
    color: "#346739",
    fontSize: 16,
    fontFamily: "Nunito_800ExtraBold",
    letterSpacing: 0.6,
  },
  stickyNav: {
    position: "fixed" as any,
    top: 0,
    left: 0,
    right: 0,
    zIndex: 100,
    flexDirection: "row" as any,
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 32,
    paddingVertical: 14,
    backgroundColor: "rgba(52, 103, 57, 0.88)",
    ...Platform.select({ web: { backdropFilter: "blur(12px)" } as any }),
  },
  navBrand: {
    flexDirection: "row" as any,
    alignItems: "center",
    gap: 10,
  },
  navIcon: {
    width: 32,
    height: 32,
    borderRadius: 8,
  },
  navName: {
    fontFamily: "Nunito_800ExtraBold",
    fontSize: 16,
    color: "#ffffff",
    letterSpacing: 0.3,
  },
  navBtn: {
    backgroundColor: "rgba(255,255,255,0.15)",
    borderWidth: 1.5,
    borderColor: "rgba(255,255,255,0.7)",
    borderRadius: 24,
    paddingVertical: 8,
    paddingHorizontal: 20,
    ...Platform.select({ web: { backdropFilter: "blur(8px)" } as any }),
  },
  navBtnText: {
    color: "#ffffff",
    fontFamily: "Nunito_800ExtraBold",
    fontSize: 14,
    letterSpacing: 0.4,
  },
  heroSection: {
    width: "100%" as any,
    minHeight: "100vh" as any,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden" as any,
  },
  heroBg: {
    ...StyleSheet.absoluteFillObject,
  },
  webScroll: {
    flex: 1,
  },
  webScrollContent: {
    flexGrow: 1,
  },
  featureSection: {
    width: "100%" as any,
    backgroundColor: "#ffffff",
    paddingVertical: 80,
    paddingHorizontal: 60,
  },
  featureSectionTinted: {
    backgroundColor: "#f8fdf8",
  },
  featureRow: {
    flexDirection: "row" as any,
    alignItems: "center",
    justifyContent: "center",
    gap: 60,
    maxWidth: 960,
    alignSelf: "center",
    width: "100%" as any,
  },
  featureIcon: {
    fontSize: 40,
    marginBottom: 12,
  },
  featureTitle: {
    fontFamily: "Nunito_800ExtraBold",
    fontSize: 28,
    color: "#346739",
    marginBottom: 14,
  },
  featureBody: {
    fontFamily: "Nunito_700Bold",
    fontSize: 16,
    color: "#555555",
    lineHeight: 26,
    maxWidth: 340,
  },
  featureTextCol: {
    flex: 1,
    maxWidth: 380,
  },
  featureMockCol: {
    flex: 1,
    maxWidth: 260,
    alignItems: "center",
  },
  phoneFrame: {
    width: 220,
    backgroundColor: "#111111",
    borderRadius: 36,
    padding: 8,
    shadowColor: "#346739",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.25,
    shadowRadius: 24,
    elevation: 12,
  },
  phoneNotch: {
    width: 60,
    height: 10,
    backgroundColor: "#222222",
    borderRadius: 8,
    alignSelf: "center",
    marginBottom: 6,
  },
  phoneScreen: {
    backgroundColor: "#f8fdf8",
    borderRadius: 28,
    overflow: "hidden",
    minHeight: 380,
    padding: 16,
  },
  mockHeader: {
    fontFamily: "Nunito_800ExtraBold",
    fontSize: 13,
    color: "#346739",
    marginBottom: 16,
    textAlign: "center",
  },
  mockScoreValue: {
    fontFamily: "Nunito_900Black",
    fontSize: 52,
    color: "#346739",
    textAlign: "center",
  },
  mockBarBg: {
    height: 10,
    backgroundColor: "#e0f0de",
    borderRadius: 8,
    marginVertical: 12,
    overflow: "hidden",
  },
  mockBarFill: {
    height: "100%" as any,
    backgroundColor: "#79AE6F",
    borderRadius: 8,
  },
  mockScoreTag: {
    fontFamily: "Nunito_700Bold",
    fontSize: 12,
    color: "#79AE6F",
    textAlign: "center",
  },
  mockCoinRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f0faf0",
    borderRadius: 12,
    padding: 10,
    marginBottom: 10,
    gap: 8,
  },
  mockCoinEmoji: {
    fontSize: 20,
  },
  mockCoinRight: {
    flex: 1,
  },
  mockCoinAmount: {
    fontFamily: "Nunito_800ExtraBold",
    fontSize: 14,
    color: "#346739",
  },
  mockCoinSub: {
    fontFamily: "Nunito_700Bold",
    fontSize: 11,
    color: "#79AE6F",
  },
  mockGardenGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: 8,
    marginTop: 8,
  },
  mockGardenEmoji: {
    fontSize: 28,
    width: 44,
    textAlign: "center",
  },
  ctaSection: {
    width: "100%" as any,
    backgroundColor: "#f8fdf8",
    paddingVertical: 100,
    alignItems: "center",
    gap: 12,
  },
  ctaSectionTitle: {
    fontFamily: "Nunito_900Black",
    fontSize: 36,
    color: "#346739",
    textAlign: "center",
  },
  ctaSectionSub: {
    fontFamily: "Nunito_700Bold",
    fontSize: 16,
    color: "#79AE6F",
    textAlign: "center",
    marginBottom: 16,
  },
  ctaSectionBtn: {
    backgroundColor: "#346739",
    paddingVertical: 14,
    paddingHorizontal: 36,
    borderRadius: 50,
    shadowColor: "#346739",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 14,
    elevation: 8,
  },
  ctaSectionBtnPressed: {
    backgroundColor: "#2d5a30",
    transform: [{ scale: 0.97 }],
  },
  ctaSectionBtnText: {
    fontFamily: "Nunito_800ExtraBold",
    fontSize: 17,
    color: "#ffffff",
    letterSpacing: 0.4,
  },
  footerSection: {
    width: "100%" as any,
    backgroundColor: "#346739",
    paddingVertical: 28,
    alignItems: "center",
  },
  footerText: {
    fontFamily: "Nunito_700Bold",
    fontSize: 13,
    color: "rgba(255,255,255,0.6)",
    letterSpacing: 0.3,
  },
});
