import { Platform, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#346739",
  },
  containerWeb: {
    minHeight: "100vh" as any,
    overflow: "visible" as any,
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.12)",
    zIndex: 1,
  },
  petalsLayer: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 2,
  },
  safe: {
    flex: 1,
    justifyContent: "center",
    paddingBottom: 80,
    zIndex: 3,
  },
  content: {
    alignItems: "center",
    paddingHorizontal: 24,
    gap: 4,
  },
  emoji: {
    fontSize: 60,
    marginBottom: 2,
  },
  flowerTreeRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 12,
  },
  taglineWrap: {
    backgroundColor: "rgba(0,0,0,0.22)",
    borderRadius: 20,
    overflow: "hidden",
    marginTop: 2,
    marginBottom: 22,
  },
  tagline: {
    fontSize: 15,
    fontFamily: "Nunito_800ExtraBold",
    color: "#ffffff",
    letterSpacing: 1.2,
    textTransform: "uppercase",
    textShadowColor: "rgba(0,0,0,0.55)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 6,
    textAlign: "center",
    paddingHorizontal: 18,
    paddingVertical: 6,
  },
  pulseRing: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 50,
    borderWidth: 2,
    borderColor: "rgba(255,255,255,0.8)",
  },
  btnWrapper: {
    alignItems: "center",
  },
  ctaButton: {
    backgroundColor: "#ffffff",
    paddingVertical: 11,
    paddingHorizontal: 30,
    borderRadius: 50,
    alignItems: "center",
    shadowColor: "#ffffff",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.55,
    shadowRadius: 14,
    elevation: 8,
    borderWidth: 1.5,
    borderColor: "rgba(255,255,255,0.6)",
  },
  ctaButtonPressed: {
    backgroundColor: "#ffffff",
    transform: [{ scale: 0.97 }],
  },
  ctaText: {
    color: "#346739",
    fontSize: 16,
    fontFamily: "Nunito_800ExtraBold",
    letterSpacing: 0.6,
  },
});

export const auth = StyleSheet.create({
  backdropOverlay: {
    backgroundColor: "rgba(0,0,0,0.45)",
  },
  backdrop: {
    flex: 1,
    justifyContent: "center",
    paddingHorizontal: 20,
    ...(Platform.OS === "web"
      ? { position: "fixed" as any, top: 0, left: 0, right: 0, bottom: 0 }
      : {}),
  },
  card: {
    backgroundColor: "#ffffff",
    borderRadius: 28,
    overflow: "hidden",
    width: "100%",
    maxWidth: 400,
    alignSelf: "center",
    maxHeight: "88%",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.25,
    shadowRadius: 20,
    elevation: 20,
  },
  gardenStrip: {
    flexDirection: "row",
    justifyContent: "space-around",
    paddingVertical: 10,
    backgroundColor: "#9FCB98",
    borderBottomWidth: 1,
    borderBottomColor: "#79AE6F",
  },
  gardenEmoji: {
    fontSize: 22,
  },
  scroll: {
    paddingHorizontal: 28,
    paddingTop: 28,
    paddingBottom: 36,
  },
  title: {
    fontFamily: "Nunito_800ExtraBold",
    fontSize: 26,
    color: "#346739",
    textAlign: "center",
    width: "100%",
    marginBottom: 4,
  },
  subtitle: {
    fontFamily: "Nunito_800ExtraBold",
    fontSize: 14,
    color: "#79AE6F",
    textAlign: "center",
    width: "100%",
    marginBottom: 20,
    letterSpacing: 0.4,
  },
  tabs: {
    flexDirection: "row",
    backgroundColor: "#9FCB98",
    borderRadius: 14,
    padding: 4,
    marginBottom: 20,
  },
  tab: {
    flex: 1,
    paddingVertical: 8,
    alignItems: "center",
    borderRadius: 10,
  },
  tabActive: {
    backgroundColor: "#ffffff",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  tabText: {
    fontFamily: "Nunito_700Bold",
    fontSize: 14,
    color: "#79AE6F",
  },
  tabTextActive: {
    color: "#346739",
    fontFamily: "Nunito_800ExtraBold",
  },
  inputWrap: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1.5,
    borderColor: "#79AE6F",
    borderRadius: 14,
    backgroundColor: "#ffffff",
    marginBottom: 12,
    paddingHorizontal: 14,
  },
  inputWrapFocused: {
    borderColor: "#346739",
    shadowColor: "#346739",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 2,
  },
  inputIcon: {
    marginRight: 10,
  },
  eyeBtn: {
    padding: 4,
    marginLeft: 6,
  },
  input: {
    flex: 1,
    fontFamily: "Nunito_700Bold",
    fontSize: 15,
    color: "#346739",
    paddingVertical: 12,
    ...Platform.select({ web: { outlineStyle: "none" as any, outlineWidth: 0 } }),
  },
  error: {
    fontFamily: "Nunito_700Bold",
    fontSize: 13,
    color: "#c0392b",
    textAlign: "center",
    marginBottom: 10,
  },
  submitBtn: {
    backgroundColor: "#346739",
    borderRadius: 16,
    paddingVertical: 14,
    alignItems: "center",
    marginTop: 4,
    shadowColor: "#346739",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.35,
    shadowRadius: 8,
    elevation: 6,
  },
  submitBtnPressed: {
    backgroundColor: "#2d5a30",
    transform: [{ scale: 0.98 }],
  },
  submitText: {
    fontFamily: "Nunito_800ExtraBold",
    fontSize: 16,
    color: "#ffffff",
    letterSpacing: 0.4,
  },
  divider: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: 16,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: "#9FCB98",
  },
  dividerText: {
    fontFamily: "Nunito_700Bold",
    fontSize: 13,
    color: "#79AE6F",
    marginHorizontal: 12,
  },
  googleBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#111111",
    borderRadius: 16,
    paddingVertical: 13,
    gap: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 4,
  },
  googleBtnPressed: {
    backgroundColor: "#2a2a2a",
    transform: [{ scale: 0.98 }],
  },
  googleText: {
    fontFamily: "Nunito_800ExtraBold",
    fontSize: 15,
    color: "#ffffff",
    letterSpacing: 0.3,
  },
  appleBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#ffffff",
    borderRadius: 16,
    paddingVertical: 13,
    gap: 10,
    marginTop: 10,
    borderWidth: 1.5,
    borderColor: "#d0d0d0",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.12,
    shadowRadius: 6,
    elevation: 4,
  },
  appleBtnPressed: {
    backgroundColor: "#f0f0f0",
    transform: [{ scale: 0.98 }],
  },
  appleText: {
    fontFamily: "Nunito_800ExtraBold",
    fontSize: 15,
    color: "#000000",
    letterSpacing: 0.3,
  },
});