import { Platform, StyleSheet } from "react-native";

export const GREEN_DARK = "#346739";
export const GREEN_MED = "#79AE6F";

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: "#f2f5f2",
  },
  scroll: {
    flex: 1,
  },
  header: {
    paddingHorizontal: 20,
    paddingBottom: 28,
    alignItems: "center",
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
  },
  headerTitle: {
    fontFamily: "Nunito_900Black",
    fontSize: 28,
    color: "#ffffff",
    textAlign: "center",
    paddingTop: 12,
    paddingBottom: 10,
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 20,
    paddingBottom: 40,
    maxWidth: 480,
    width: "100%",
    alignSelf: "center",
  },
  banner: {
    borderRadius: 16,
    padding: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 20,
  },
  bannerLeft: {
    flex: 1,
    paddingRight: 12,
  },
  bannerKicker: {
    fontFamily: "Nunito_700Bold",
    fontSize: 11,
    color: "#9FCB98",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 4,
  },
  bannerTitle: {
    fontFamily: "Nunito_800ExtraBold",
    fontSize: 15,
    color: "#ffffff",
    lineHeight: 21,
    marginBottom: 10,
  },
  bannerCta: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: "rgba(255,255,255,0.15)",
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 5,
    gap: 4,
  },
  bannerCtaText: {
    fontFamily: "Nunito_700Bold",
    fontSize: 12,
    color: "#ffffff",
  },
  bannerCoinImg: {
    width: 56,
    height: 56,
  },
  profileCard: {
    backgroundColor: "#ffffff",
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.07,
    shadowRadius: 6,
    elevation: 2,
  },
  profileRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    paddingBottom: 16,
  },
  cardDivider: {
    height: 1,
    backgroundColor: "rgba(0,0,0,0.07)",
  },
  avatarBtn: {
    position: "relative",
  },
  avatar: {
    width: 56,
    height: 56,
    borderRadius: 28,
    borderWidth: 2.5,
    borderColor: GREEN_MED,
  },
  avatarEditBadge: {
    position: "absolute",
    bottom: -1,
    right: -1,
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: GREEN_DARK,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1.5,
    borderColor: "#ffffff",
  },
  profileInfo: {
    flex: 1,
  },
  profileName: {
    fontFamily: "Nunito_800ExtraBold",
    fontSize: 16,
    color: "#1a2e1b",
    marginBottom: 2,
  },
  profileEmail: {
    fontFamily: "Nunito_700Bold",
    fontSize: 13,
    color: "#6b7f6b",
  },
  syncRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 14,
  },
  syncRowPressed: {
    opacity: 0.7,
  },
  syncLabel: {
    fontFamily: "Nunito_800ExtraBold",
    fontSize: 14,
    color: "#1a2e1b",
    flex: 1,
  },
  syncSubLabel: {
    fontFamily: "Nunito_700Bold",
    fontSize: 12,
    color: "#6b7f6b",
  },
  modalBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.45)",
    justifyContent: "center",
    alignItems: "center",
  },
  avatarModal: {
    backgroundColor: "#ffffff",
    borderRadius: 20,
    padding: 24,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 20,
    elevation: 10,
  },
  avatarModalTitle: {
    fontFamily: "Nunito_900Black",
    fontSize: 18,
    color: "#1a2e1b",
    marginBottom: 20,
  },
  avatarRow: {
    flexDirection: "row",
    gap: 16,
  },
  avatarOption: {
    width: 80,
    height: 80,
    borderRadius: 40,
    borderWidth: 3,
    borderColor: "transparent",
    overflow: "hidden",
  },
  avatarOptionSelected: {
    borderColor: GREEN_DARK,
  },
  avatarOptionImg: {
    width: 74,
    height: 74,
    borderRadius: 37,
  },
  manageCard: {
    backgroundColor: "#ffffff",
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 4,
    marginTop: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.07,
    shadowRadius: 6,
    elevation: 2,
  },
  manageCardTitle: {
    fontFamily: "Nunito_900Black",
    fontSize: 13,
    color: "#6b7f6b",
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: 10,
  },
  manageRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 14,
  },
  manageRowPressed: {
    opacity: 0.7,
  },
  manageRowDisabled: {
    opacity: 0.4,
  },
  manageRowLabel: {
    fontFamily: "Nunito_800ExtraBold",
    fontSize: 14,
    color: "#1a2e1b",
    flex: 1,
  },
  manageRowLabelDisabled: {
    color: "#b0b8b0",
  },
  nameModal: {
    backgroundColor: "#ffffff",
    borderRadius: 20,
    padding: 24,
    width: "100%",
    maxWidth: 340,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 20,
    elevation: 10,
  },
  nameModalTitle: {
    fontFamily: "Nunito_900Black",
    fontSize: 18,
    color: "#1a2e1b",
    marginBottom: 16,
    textAlign: "center",
  },
  nameInput: {
    borderWidth: 1.5,
    borderColor: "#9FCB98",
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
    fontFamily: "Nunito_700Bold",
    fontSize: 15,
    color: "#1a2e1b",
    width: "100%",
    marginBottom: 20,
    ...Platform.select({ web: { outlineStyle: "none", outlineWidth: 0 } }),
  },
  nameModalButtons: {
    flexDirection: "row",
    gap: 10,
    width: "100%",
  },
  nameModalBtn: {
    flex: 1,
    paddingVertical: 11,
    borderRadius: 12,
    alignItems: "center",
    backgroundColor: "#f2f5f2",
  },
  nameModalBtnPrimary: {
    flex: 1,
    paddingVertical: 11,
    borderRadius: 12,
    alignItems: "center",
    backgroundColor: "#346739",
  },
  nameModalBtnLabel: {
    fontFamily: "Nunito_800ExtraBold",
    fontSize: 14,
    color: "#346739",
  },
  nameModalBtnPrimaryLabel: {
    fontFamily: "Nunito_800ExtraBold",
    fontSize: 14,
    color: "#ffffff",
  },
  nameEditBadge: {
    position: "absolute",
    top: -4,
    right: -4,
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: "#346739",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1.5,
    borderColor: "#ffffff",
  },
  profileNameWrapper: {
    position: "relative",
    alignSelf: "flex-start",
  },
});
