import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#121212",
  },
  scrollContainer: {
    flex: 1,
    width: "100%",
  },
  scrollBase: {
    flexGrow: 1,
  },
  container: {
    flex: 1,
    paddingBottom: 48,
    alignItems: "center",
    minHeight: "100%",
    width: "100%",
    position: "relative",
    backgroundColor: "#121212",
  },
  contentWrapper: {
    flex: 1,
    width: "100%",
    maxWidth: 500,
    alignItems: "center",
    zIndex: 1,
    paddingHorizontal: 20,
  },
  backButton: {
    alignSelf: "flex-start",
    marginTop: 16,
    marginBottom: 8,
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 10,
    backgroundColor: "rgba(255,255,255,0.06)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
  },
  backButtonText: {
    color: "#AAAAAA",
    fontSize: 14,
    fontWeight: "600",
  },
  headerSection: {
    alignItems: "center",
    marginBottom: 20,
    marginTop: 16,
  },
  logoContainer: {
    width: 90,
    height: 90,
    borderRadius: 45,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 16,
    backgroundColor: "#E8F5E9",
    shadowColor: "#4CAF50",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.5,
    shadowRadius: 12,
    elevation: 8,
  },
  logoEmoji: {
    fontSize: 46,
  },
  mainTitle: {
    fontSize: 34,
    fontWeight: "900",
    marginBottom: 10,
    textAlign: "center",
    color: "#E8F5E9",
    letterSpacing: 0.5,
  },
  subtitle: {
    fontSize: 14,
    textAlign: "center",
    lineHeight: 22,
    color: "#7CB87A",
  },
  grassRow: {
    flexDirection: "row",
    justifyContent: "center",
    gap: 6,
    marginVertical: 8,
    width: "100%",
  },
  grassEmoji: {
    fontSize: 20,
  },
  separatorContainer: {
    width: "100%",
    alignItems: "center",
    marginVertical: 4,
    gap: 4,
  },
  separatorLine: {
    width: "60%",
    height: 1,
    backgroundColor: "rgba(76,175,80,0.15)",
  },
  separatorEmojis: {
    flexDirection: "row",
    gap: 16,
    justifyContent: "center",
    paddingVertical: 6,
  },
  separatorEmoji: {
    fontSize: 22,
  },
  cardOuter: {
    width: "100%",
    shadowOffset: { width: 0, height: 6 },
    shadowRadius: 16,
    elevation: 10,
    marginVertical: 4,
  },
  card: {
    borderRadius: 18,
    padding: 20,
    gap: 12,
  },
  nailRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 8,
  },
  nail: {
    width: 10,
    height: 10,
    borderRadius: 5,
    opacity: 0.8,
  },
  emojiSection: {
    alignItems: "center",
    gap: 8,
  },
  emojiBubble: {
    width: 80,
    height: 80,
    borderRadius: 40,
    justifyContent: "center",
    alignItems: "center",
  },
  phaseEmoji: {
    fontSize: 40,
  },
  activeBadge: {
    backgroundColor: "rgba(76,175,80,0.25)",
    borderWidth: 1,
    borderColor: "rgba(76,175,80,0.6)",
    borderRadius: 20,
    paddingVertical: 5,
    paddingHorizontal: 14,
  },
  activeBadgeText: {
    color: "#81C784",
    fontSize: 13,
    fontWeight: "700",
  },
  growthRow: {
    flexDirection: "row",
    justifyContent: "center",
    gap: 8,
    marginTop: 2,
  },
  growthStage: {
    fontSize: 16,
    opacity: 0.2,
  },
  growthStagePast: {
    opacity: 0.5,
  },
  growthStageCurrent: {
    opacity: 1,
    fontSize: 24,
  },
  cardTitle: {
    fontSize: 20,
    fontWeight: "800",
    textAlign: "center",
    color: "#D4A853",
    letterSpacing: 0.3,
  },
  cardTitleActive: {
    color: "#81C784",
  },
  cardSubtitle: {
    fontSize: 12,
    textAlign: "center",
    color: "#7A6040",
    fontStyle: "italic",
  },
  cardDivider: {
    height: 1,
    borderRadius: 1,
    marginVertical: 2,
  },
  itemsContainer: {
    gap: 10,
  },
  itemRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
  },
  itemBullet: {
    fontSize: 14,
    marginTop: 2,
    color: "#666",
  },
  itemText: {
    fontSize: 14,
    color: "#C8B99A",
    flex: 1,
    lineHeight: 20,
  },
  itemTextUpcoming: {
    color: "#6B5A42",
  },
  taglineBox: {
    borderWidth: 1,
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 14,
    marginTop: 4,
  },
  taglineText: {
    fontSize: 13,
    fontStyle: "italic",
    color: "#7A6040",
    lineHeight: 18,
    textAlign: "center",
  },
  taglineTextActive: {
    color: "#81C784",
  },
  footerSign: {
    alignItems: "center",
    marginTop: 20,
    marginBottom: 8,
  },
  footerSignPost: {
    width: 8,
    height: 28,
    backgroundColor: "#5C3D1A",
    borderRadius: 4,
  },
  footerSignBoard: {
    backgroundColor: "#1E1008",
    borderWidth: 2,
    borderColor: "#5C3D1A",
    borderRadius: 12,
    paddingVertical: 18,
    paddingHorizontal: 24,
    alignItems: "center",
    gap: 10,
    maxWidth: 320,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 6,
  },
  footerSignNail: {
    color: "#8B6914",
    fontSize: 10,
    letterSpacing: 12,
  },
  footerText: {
    fontSize: 14,
    fontStyle: "italic",
    textAlign: "center",
    lineHeight: 22,
    color: "#9A8060",
  },
});
