import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: "#f0f0ea",
  },

  // ── Header ────────────────────────────────────────────────────────────────
  header: {
    paddingBottom: 32,
  },
  headerInner: {
    paddingTop: 20,
    paddingHorizontal: 16,
    paddingBottom: 8,
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "flex-end",
  },
  headerInnerMobile: {
    paddingLeft: 64,
    justifyContent: "flex-end",
  },
  headerText: {
    flex: 1,
    paddingRight: 12,
    alignItems: "center",
  },
  headerTextWeb: {
    flex: undefined,
    position: "absolute",
    left: 16,
    right: 16,
    alignItems: "center",
    paddingRight: 0,
  },
  headerTitle: {
    fontFamily: "Nunito_900Black",
    fontSize: 22,
    color: "#ffffff",
    marginBottom: 4,
    textAlign: "center",
  },
  headerTitleWeb: {
    fontSize: 28,
  },
  headerSubtitle: {
    fontFamily: "Nunito_700Bold",
    fontSize: 17,
    color: "#9FCB98",
    textAlign: "center",
  },
  coinWidget: {
    flexDirection: "row",
    alignItems: "center",
    marginLeft: 12,
  },
  coinImg: {
    width: 40,
    height: 40,
    resizeMode: "contain",
    marginRight: -15,
    zIndex: 1,
  },
  coinBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.22)",
    paddingLeft: 20,
    paddingRight: 10,
    paddingVertical: 6,
    borderRadius: 16,
  },
  coinText: {
    fontFamily: "Nunito_800ExtraBold",
    fontSize: 14,
    color: "#FFE566",
  },

  // ── Scroll ────────────────────────────────────────────────────────────────
  scroll: {
    flex: 1,
    marginTop: -20,
  },
  scrollContent: {
    paddingTop: 24,
    paddingBottom: 48,
    backgroundColor: "#f0f0ea",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
  },
  inner: {
    paddingHorizontal: 16,
  },
  innerWeb: {
    flex: 1,
    maxWidth: 900,
  },
  webContentRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "center",
  },
  webSpacer: {
    width: 230,
  },
  sideCol: {
    width: 210,
    marginLeft: 20,
    gap: 12,
  },

  // ── Info row (Daily Bonus + Progress) ────────────────────────────────────
  infoRow: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 20,
  },
  infoCard: {
    flex: 1,
    backgroundColor: "#e8f0e8",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#c8dcc8",
    padding: 14,
    shadowColor: "#346739",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.07,
    shadowRadius: 5,
    elevation: 2,
  },
  infoIconBadge: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: "rgba(52,103,57,0.10)",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
  },
  infoCardTitle: {
    fontFamily: "Nunito_800ExtraBold",
    fontSize: 13,
    color: "#1f4a25",
    marginBottom: 2,
  },
  infoCardHint: {
    fontFamily: "Nunito_700Bold",
    fontSize: 11,
    color: "#8a968c",
    marginBottom: 6,
  },
  infoCardMuted: {
    fontFamily: "Nunito_700Bold",
    fontSize: 10,
    color: "#8a968c",
    marginTop: 4,
  },
  infoCountdown: {
    fontFamily: "Nunito_900Black",
    fontSize: 22,
    color: "#1f4a25",
  },
  infoCountdownMuted: {
    fontFamily: "Nunito_700Bold",
    fontSize: 16,
    color: "#8a968c",
  },
  progressTrack: {
    height: 6,
    backgroundColor: "#c8dcc8",
    borderRadius: 3,
    overflow: "hidden",
    marginTop: 8,
  },
  progressFill: {
    height: "100%",
    backgroundColor: "#346739",
    borderRadius: 3,
  },

  // ── Feature banner ────────────────────────────────────────────────────────
  banner: {
    borderRadius: 20,
    padding: 20,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginBottom: 20,
    overflow: "hidden",
  },
  bannerLeft: {
    flex: 1,
  },
  bannerKicker: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    backgroundColor: "rgba(159,203,152,0.18)",
    borderWidth: 1,
    borderColor: "rgba(159,203,152,0.35)",
    borderRadius: 999,
    paddingVertical: 3,
    paddingHorizontal: 10,
    alignSelf: "flex-start",
    marginBottom: 10,
  },
  bannerKickerText: {
    fontFamily: "Nunito_800ExtraBold",
    fontSize: 10,
    color: "#9FCB98",
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  bannerTitle: {
    fontFamily: "Nunito_900Black",
    fontSize: 20,
    color: "#ffffff",
    lineHeight: 26,
    marginBottom: 6,
  },
  bannerTitleEm: {
    color: "#9FCB98",
  },
  bannerSubtitle: {
    fontFamily: "Nunito_700Bold",
    fontSize: 12,
    color: "rgba(255,255,255,0.82)",
    marginBottom: 12,
  },
  bannerCta: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "#ffffff",
    borderRadius: 999,
    paddingVertical: 8,
    paddingHorizontal: 14,
    alignSelf: "flex-start",
  },
  bannerCtaText: {
    fontFamily: "Nunito_800ExtraBold",
    fontSize: 12,
    color: "#1f4a25",
  },
  bannerImgFrame: {
    width: 96,
    height: 96,
    borderRadius: 16,
    backgroundColor: "#f4efe2",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    borderWidth: 3,
    borderColor: "rgba(255,255,255,0.2)",
  },
  bannerImg: {
    width: "90%",
    height: "90%",
  },

  // ── Search bar ────────────────────────────────────────────────────────────
  searchBar: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#e3e5dc",
    borderRadius: 999,
    paddingVertical: 10,
    paddingHorizontal: 14,
    marginBottom: 16,
  },
  searchInput: {
    flex: 1,
    fontFamily: "Nunito_700Bold",
    fontSize: 14,
    color: "#1a2a1d",
  },

  // ── Section header ────────────────────────────────────────────────────────
  sectionTitle: {
    fontFamily: "Nunito_900Black",
    fontSize: 18,
    color: "#1f4a25",
    marginBottom: 12,
  },

  // ── Grid ─────────────────────────────────────────────────────────────────
  grid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    marginBottom: 24,
  },

  // ── Flower card ───────────────────────────────────────────────────────────
  card: {},
  cardBody: {
    backgroundColor: "#ffffff",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#e3e5dc",
    padding: 10,
    overflow: "hidden",
    marginBottom: 6,
    shadowColor: "#346739",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 2,
  },
  cardBadge: {
    position: "absolute",
    top: 8,
    right: 8,
    paddingVertical: 2,
    paddingHorizontal: 7,
    borderRadius: 999,
    zIndex: 1,
  },
  cardBadgeText: {
    fontFamily: "Nunito_800ExtraBold",
    fontSize: 9,
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  cardImgFrame: {
    width: "100%",
    aspectRatio: 1,
    borderRadius: 12,
    backgroundColor: "#f4efe2",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  cardImg: {
    width: "88%",
    height: "88%",
  },
  cardLockOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: "center",
    justifyContent: "center",
  },
  cardName: {
    fontFamily: "Nunito_800ExtraBold",
    fontSize: 13,
    color: "#1f4a25",
    textAlign: "center",
    marginTop: 8,
    marginBottom: 2,
  },
  cardPriceRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
  },
  cardCoinImg: {
    width: 16,
    height: 16,
    borderRadius: 8,
  },
  cardPriceText: {
    fontFamily: "Nunito_800ExtraBold",
    fontSize: 13,
    color: "#c99a2a",
  },
  cardPriceMoney: {
    fontFamily: "Nunito_800ExtraBold",
    fontSize: 13,
    color: "#346739",
  },

  // ── Buy modal ─────────────────────────────────────────────────────────────
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.45)",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 20,
  },
  modalCard: {
    width: "100%",
    maxWidth: 400,
    backgroundColor: "#ffffff",
    borderRadius: 24,
    padding: 28,
    alignItems: "center",
  },
  modalImgFrame: {
    width: 120,
    height: 120,
    borderRadius: 20,
    backgroundColor: "#f4efe2",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    marginBottom: 16,
    borderWidth: 3,
    borderColor: "#e3e5dc",
  },
  modalImg: {
    width: "88%",
    height: "88%",
  },
  modalName: {
    fontFamily: "Nunito_900Black",
    fontSize: 22,
    color: "#1f4a25",
    marginBottom: 8,
  },
  modalDescription: {
    fontFamily: "Nunito_600SemiBold",
    fontSize: 13,
    color: "#5a7a5e",
    textAlign: "center",
    marginBottom: 16,
    paddingHorizontal: 8,
  },
  modalPriceRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 24,
  },
  modalCoinImg: {
    width: 22,
    height: 22,
    borderRadius: 11,
  },
  modalPrice: {
    fontFamily: "Nunito_800ExtraBold",
    fontSize: 20,
    color: "#c99a2a",
  },
  modalPriceMoney: {
    fontFamily: "Nunito_800ExtraBold",
    fontSize: 20,
    color: "#346739",
  },
  modalBuyBtn: {
    width: "100%",
    paddingVertical: 14,
    borderRadius: 14,
    backgroundColor: "#346739",
    alignItems: "center",
    marginBottom: 10,
    shadowColor: "#1f4a25",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 4,
  },
  modalBuyBtnText: {
    fontFamily: "Nunito_800ExtraBold",
    fontSize: 15,
    color: "#ffffff",
  },
  modalCancelBtn: {
    paddingVertical: 10,
  },
  modalCancelText: {
    fontFamily: "Nunito_700Bold",
    fontSize: 14,
    color: "#8a968c",
  },

  // ── Toast ─────────────────────────────────────────────────────────────────
  toast: {
    position: "absolute",
    top: 120,
    alignSelf: "center",
    zIndex: 999,
    backgroundColor: "#346739",
    borderRadius: 14,
    paddingVertical: 14,
    paddingHorizontal: 24,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 8,
  },
  toastText: {
    fontFamily: "Nunito_800ExtraBold",
    fontSize: 14,
    color: "#ffffff",
  },
});
